homebrew_taps: []

homebrew_install_packages:
  - git
  - git-delta
  - fzf
  - fd
  - nvim
  - tmux
  - most
  - bat
  - eza
  - htop
  - btop
  - python3
  - scrcpy
  - ghostty
  - rectangle
  - itsycal
  - jetbrains-toolbox
  - font-jetbrains-mono-nerd-font

sdkman_java_version: "21.0.11-jbr"
