---

- name: Ensure .config/git directory exists
  ansible.builtin.file:
    path: "~/.config/git"
    state: directory

- name: Copy git config to .config directory
  ansible.builtin.copy:
    src: "files/config/git/config"
    dest: "~/.config/git/config"
    backup: true

- name: Copy global gitignore to .config directory
  ansible.builtin.copy:
    src: "files/config/git/ignore"
    dest: "~/.config/git/ignore"
    backup: true

- name: Ensure .config/nvim directory exists
  ansible.builtin.file:
    path: "~/.config/nvim"
    state: directory

- name: Copy init.vim to .config directory
  ansible.builtin.copy:
    src: "files/config/nvim/init.vim"
    dest: "~/.config/nvim/init.vim"
    backup: true

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory

- name: Copy ssh config
  ansible.builtin.copy:
    src: "files/config/ssh/config"
    dest: "~/.ssh/config"
    backup: true

- name: Ensure .config/tmux directory exists
  ansible.builtin.file:
    path: "~/.config/tmux"
    state: directory

- name: Copy tmux config
  ansible.builtin.copy:
    src: "files/config/tmux/tmux.conf"
    dest: "~/.config/tmux/tmux.conf"
    backup: true

- name: Ensure Tmux Plugin Manager (TPM) is installed
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.tmux/plugins/tpm"
    update: true

- name: Ensure .config/ghostty directory exists
  ansible.builtin.file:
    path: "~/.config/ghostty"
    state: directory

- name: Copy ghostty config
  ansible.builtin.copy:
    src: "files/config/ghostty/config"
    dest: "~/.config/ghostty/config"
    backup: true

- name: Ensure .config/micro directory exists
  ansible.builtin.file:
    path: "~/.config/micro"
    state: directory

- name: Copy micro settings
  ansible.builtin.copy:
    src: "files/config/micro/settings.json"
    dest: "~/.config/micro/settings.json"
    backup: true


