---
- name: Set up zshrc and oh-my-zsh
  ansible.builtin.include_tasks: zsh.yml

- name: Set up config files
  ansible.builtin.include_tasks: config-files.yml

- name: Set up "~/dev" directory
  ansible.builtin.include_tasks: dev-directory.yml
